// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: server/hydrakv.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDBRequest) Reset() {
	*x = CreateDBRequest{}
	mi := &file_server_hydrakv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDBRequest) ProtoMessage() {}

func (x *CreateDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDBRequest.ProtoReflect.Descriptor instead.
func (*CreateDBRequest) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDBRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Db            string                 `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Apikey        string                 `protobuf:"bytes,2,opt,name=apikey,proto3" json:"apikey,omitempty"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_server_hydrakv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{1}
}

func (x *SetRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *SetRequest) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *SetRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Db            string                 `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Apikey        string                 `protobuf:"bytes,2,opt,name=apikey,proto3" json:"apikey,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_server_hydrakv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *GetRequest) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Db            string                 `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Apikey        string                 `protobuf:"bytes,2,opt,name=apikey,proto3" json:"apikey,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_server_hydrakv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *DeleteRequest) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IncrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Db            string                 `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Apikey        string                 `protobuf:"bytes,2,opt,name=apikey,proto3" json:"apikey,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrRequest) Reset() {
	*x = IncrRequest{}
	mi := &file_server_hydrakv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrRequest) ProtoMessage() {}

func (x *IncrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrRequest.ProtoReflect.Descriptor instead.
func (*IncrRequest) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{4}
}

func (x *IncrRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *IncrRequest) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *IncrRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IncrRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type ExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Db            string                 `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsRequest) Reset() {
	*x = ExistsRequest{}
	mi := &file_server_hydrakv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsRequest) ProtoMessage() {}

func (x *ExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsRequest.ProtoReflect.Descriptor instead.
func (*ExistsRequest) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{5}
}

func (x *ExistsRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

type OKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OKResponse) Reset() {
	*x = OKResponse{}
	mi := &file_server_hydrakv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OKResponse) ProtoMessage() {}

func (x *OKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OKResponse.ProtoReflect.Descriptor instead.
func (*OKResponse) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{6}
}

func (x *OKResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CreateDBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Apikey        string                 `protobuf:"bytes,2,opt,name=apikey,proto3" json:"apikey,omitempty"`
	Created       bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Exists        bool                   `protobuf:"varint,4,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDBResponse) Reset() {
	*x = CreateDBResponse{}
	mi := &file_server_hydrakv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDBResponse) ProtoMessage() {}

func (x *CreateDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDBResponse.ProtoReflect.Descriptor instead.
func (*CreateDBResponse) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDBResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDBResponse) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *CreateDBResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *CreateDBResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_server_hydrakv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{8}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsResponse) Reset() {
	*x = ExistsResponse{}
	mi := &file_server_hydrakv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResponse) ProtoMessage() {}

func (x *ExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResponse.ProtoReflect.Descriptor instead.
func (*ExistsResponse) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{9}
}

func (x *ExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type FiFoLiFoDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FiFoLiFoDeleteRequest) Reset() {
	*x = FiFoLiFoDeleteRequest{}
	mi := &file_server_hydrakv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FiFoLiFoDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiFoLiFoDeleteRequest) ProtoMessage() {}

func (x *FiFoLiFoDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiFoLiFoDeleteRequest.ProtoReflect.Descriptor instead.
func (*FiFoLiFoDeleteRequest) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{10}
}

func (x *FiFoLiFoDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FiFoLiFoPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FiFoLiFoPushRequest) Reset() {
	*x = FiFoLiFoPushRequest{}
	mi := &file_server_hydrakv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FiFoLiFoPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiFoLiFoPushRequest) ProtoMessage() {}

func (x *FiFoLiFoPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiFoLiFoPushRequest.ProtoReflect.Descriptor instead.
func (*FiFoLiFoPushRequest) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{11}
}

func (x *FiFoLiFoPushRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FiFoLiFoPushRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FiFoLiFoPopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FiFoLiFoPopRequest) Reset() {
	*x = FiFoLiFoPopRequest{}
	mi := &file_server_hydrakv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FiFoLiFoPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiFoLiFoPopRequest) ProtoMessage() {}

func (x *FiFoLiFoPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiFoLiFoPopRequest.ProtoReflect.Descriptor instead.
func (*FiFoLiFoPopRequest) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{12}
}

func (x *FiFoLiFoPopRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FiFoLiFoPopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FiFoLiFoPopResponse) Reset() {
	*x = FiFoLiFoPopResponse{}
	mi := &file_server_hydrakv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FiFoLiFoPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiFoLiFoPopResponse) ProtoMessage() {}

func (x *FiFoLiFoPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiFoLiFoPopResponse.ProtoReflect.Descriptor instead.
func (*FiFoLiFoPopResponse) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{13}
}

func (x *FiFoLiFoPopResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_server_hydrakv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_hydrakv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_server_hydrakv_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_server_hydrakv_proto protoreflect.FileDescriptor

const file_server_hydrakv_proto_rawDesc = "" +
	"\n" +
	"\x14server/hydrakv.proto\x12\x02kv\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\x0fCreateDBRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"n\n" +
	"\n" +
	"SetRequest\x12\x0e\n" +
	"\x02db\x18\x01 \x01(\tR\x02db\x12\x16\n" +
	"\x06apikey\x18\x02 \x01(\tR\x06apikey\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\"F\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02db\x18\x01 \x01(\tR\x02db\x12\x16\n" +
	"\x06apikey\x18\x02 \x01(\tR\x06apikey\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"I\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02db\x18\x01 \x01(\tR\x02db\x12\x16\n" +
	"\x06apikey\x18\x02 \x01(\tR\x06apikey\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"_\n" +
	"\vIncrRequest\x12\x0e\n" +
	"\x02db\x18\x01 \x01(\tR\x02db\x12\x16\n" +
	"\x06apikey\x18\x02 \x01(\tR\x06apikey\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"\x1f\n" +
	"\rExistsRequest\x12\x0e\n" +
	"\x02db\x18\x01 \x01(\tR\x02db\"\x1c\n" +
	"\n" +
	"OKResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"p\n" +
	"\x10CreateDBResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06apikey\x18\x02 \x01(\tR\x06apikey\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\x12\x16\n" +
	"\x06exists\x18\x04 \x01(\bR\x06exists\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"(\n" +
	"\x0eExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"+\n" +
	"\x15FiFoLiFoDeleteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"?\n" +
	"\x13FiFoLiFoPushRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"(\n" +
	"\x12FiFoLiFoPopRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x13FiFoLiFoPopResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xef\x04\n" +
	"\tKVService\x125\n" +
	"\bCreateDB\x12\x13.kv.CreateDBRequest\x1a\x14.kv.CreateDBResponse\x12%\n" +
	"\x03Set\x12\x0e.kv.SetRequest\x1a\x0e.kv.OKResponse\x12'\n" +
	"\x05SetNX\x12\x0e.kv.SetRequest\x1a\x0e.kv.OKResponse\x12'\n" +
	"\x04Incr\x12\x0f.kv.IncrRequest\x1a\x0e.kv.OKResponse\x12&\n" +
	"\x03Get\x12\x0e.kv.GetRequest\x1a\x0f.kv.GetResponse\x12+\n" +
	"\x06Delete\x12\x11.kv.DeleteRequest\x1a\x0e.kv.OKResponse\x12/\n" +
	"\x06Exists\x12\x11.kv.ExistsRequest\x1a\x12.kv.ExistsResponse\x12;\n" +
	"\x0eFiFoLiFoDelete\x12\x19.kv.FiFoLiFoDeleteRequest\x1a\x0e.kv.OKResponse\x127\n" +
	"\fFiFoLiFoPush\x12\x17.kv.FiFoLiFoPushRequest\x1a\x0e.kv.OKResponse\x12?\n" +
	"\fFiFoLiFoFPop\x12\x16.kv.FiFoLiFoPopRequest\x1a\x17.kv.FiFoLiFoPopResponse\x12?\n" +
	"\fFiFoLiFoLPop\x12\x16.kv.FiFoLiFoPopRequest\x1a\x17.kv.FiFoLiFoPopResponse\x124\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x12.kv.HealthResponseB(Z&hydrakv/server/hydrakv/proto/kvpb;kvpbb\x06proto3"

var (
	file_server_hydrakv_proto_rawDescOnce sync.Once
	file_server_hydrakv_proto_rawDescData []byte
)

func file_server_hydrakv_proto_rawDescGZIP() []byte {
	file_server_hydrakv_proto_rawDescOnce.Do(func() {
		file_server_hydrakv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_hydrakv_proto_rawDesc), len(file_server_hydrakv_proto_rawDesc)))
	})
	return file_server_hydrakv_proto_rawDescData
}

var file_server_hydrakv_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_server_hydrakv_proto_goTypes = []any{
	(*CreateDBRequest)(nil),       // 0: kv.CreateDBRequest
	(*SetRequest)(nil),            // 1: kv.SetRequest
	(*GetRequest)(nil),            // 2: kv.GetRequest
	(*DeleteRequest)(nil),         // 3: kv.DeleteRequest
	(*IncrRequest)(nil),           // 4: kv.IncrRequest
	(*ExistsRequest)(nil),         // 5: kv.ExistsRequest
	(*OKResponse)(nil),            // 6: kv.OKResponse
	(*CreateDBResponse)(nil),      // 7: kv.CreateDBResponse
	(*GetResponse)(nil),           // 8: kv.GetResponse
	(*ExistsResponse)(nil),        // 9: kv.ExistsResponse
	(*FiFoLiFoDeleteRequest)(nil), // 10: kv.FiFoLiFoDeleteRequest
	(*FiFoLiFoPushRequest)(nil),   // 11: kv.FiFoLiFoPushRequest
	(*FiFoLiFoPopRequest)(nil),    // 12: kv.FiFoLiFoPopRequest
	(*FiFoLiFoPopResponse)(nil),   // 13: kv.FiFoLiFoPopResponse
	(*HealthResponse)(nil),        // 14: kv.HealthResponse
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_server_hydrakv_proto_depIdxs = []int32{
	0,  // 0: kv.KVService.CreateDB:input_type -> kv.CreateDBRequest
	1,  // 1: kv.KVService.Set:input_type -> kv.SetRequest
	1,  // 2: kv.KVService.SetNX:input_type -> kv.SetRequest
	4,  // 3: kv.KVService.Incr:input_type -> kv.IncrRequest
	2,  // 4: kv.KVService.Get:input_type -> kv.GetRequest
	3,  // 5: kv.KVService.Delete:input_type -> kv.DeleteRequest
	5,  // 6: kv.KVService.Exists:input_type -> kv.ExistsRequest
	10, // 7: kv.KVService.FiFoLiFoDelete:input_type -> kv.FiFoLiFoDeleteRequest
	11, // 8: kv.KVService.FiFoLiFoPush:input_type -> kv.FiFoLiFoPushRequest
	12, // 9: kv.KVService.FiFoLiFoFPop:input_type -> kv.FiFoLiFoPopRequest
	12, // 10: kv.KVService.FiFoLiFoLPop:input_type -> kv.FiFoLiFoPopRequest
	15, // 11: kv.KVService.Health:input_type -> google.protobuf.Empty
	7,  // 12: kv.KVService.CreateDB:output_type -> kv.CreateDBResponse
	6,  // 13: kv.KVService.Set:output_type -> kv.OKResponse
	6,  // 14: kv.KVService.SetNX:output_type -> kv.OKResponse
	6,  // 15: kv.KVService.Incr:output_type -> kv.OKResponse
	8,  // 16: kv.KVService.Get:output_type -> kv.GetResponse
	6,  // 17: kv.KVService.Delete:output_type -> kv.OKResponse
	9,  // 18: kv.KVService.Exists:output_type -> kv.ExistsResponse
	6,  // 19: kv.KVService.FiFoLiFoDelete:output_type -> kv.OKResponse
	6,  // 20: kv.KVService.FiFoLiFoPush:output_type -> kv.OKResponse
	13, // 21: kv.KVService.FiFoLiFoFPop:output_type -> kv.FiFoLiFoPopResponse
	13, // 22: kv.KVService.FiFoLiFoLPop:output_type -> kv.FiFoLiFoPopResponse
	14, // 23: kv.KVService.Health:output_type -> kv.HealthResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_server_hydrakv_proto_init() }
func file_server_hydrakv_proto_init() {
	if File_server_hydrakv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_hydrakv_proto_rawDesc), len(file_server_hydrakv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_hydrakv_proto_goTypes,
		DependencyIndexes: file_server_hydrakv_proto_depIdxs,
		MessageInfos:      file_server_hydrakv_proto_msgTypes,
	}.Build()
	File_server_hydrakv_proto = out.File
	file_server_hydrakv_proto_goTypes = nil
	file_server_hydrakv_proto_depIdxs = nil
}
